from typing import Protocol, runtime_checkable

@runtime_checkable
class LoggerLikeProtocol(Protocol):
    """Minimal logger surface compatible with logging.Logger."""
    def debug(self, msg: str, *args, **kwargs) -> None: ...
    def info(self, msg: str, *args, **kwargs) -> None: ...
    def warning(self, msg: str, *args, **kwargs) -> None: ...
    def error(self, msg: str, *args, **kwargs) -> None: ...

class LoggerFactoryProtocol(Protocol):
    def get_logger(self, name: str) -> LoggerLikeProtocol: ...